//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Data/Controls/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""PlayerCharacterInput"",
            ""id"": ""c0b50e6d-9280-470c-98fa-6182be604fba"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""9e2968dc-4133-4c5e-bc63-0d298699de19"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""f9011add-67ea-44f9-bbc4-6dae8804cc71"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c4d59952-4451-45bf-905c-2a30cdec94ce"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0a80272e-6156-433f-b070-494b6f51b088"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""71fcbd63-35fc-42fa-a9ca-b6e5c75d856c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""90fb0dfd-bae2-4059-84a8-56c6653b0f4b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""PlayerAbilityInput"",
            ""id"": ""221f6d17-48bf-48eb-86d9-4bc258a1183d"",
            ""actions"": [
                {
                    ""name"": ""AbilityTrigger"",
                    ""type"": ""Button"",
                    ""id"": ""807186ef-5213-44d1-aca2-2aecd3e04bda"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""05beac4d-4bbe-4643-9903-3472011a1455"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99added2-db75-4fa3-abc5-ed2d7103ff94"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb02a4e3-f4bd-4e32-90d0-cf4e9b250fb7"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24541db9-6b2d-4603-9f47-3ff82c6bf5e3"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ca99e65-20d1-45cd-805a-f54f8c5bdc19"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerCharacterInput
        m_PlayerCharacterInput = asset.FindActionMap("PlayerCharacterInput", throwIfNotFound: true);
        m_PlayerCharacterInput_Move = m_PlayerCharacterInput.FindAction("Move", throwIfNotFound: true);
        // PlayerAbilityInput
        m_PlayerAbilityInput = asset.FindActionMap("PlayerAbilityInput", throwIfNotFound: true);
        m_PlayerAbilityInput_AbilityTrigger = m_PlayerAbilityInput.FindAction("AbilityTrigger", throwIfNotFound: true);
    }

    ~@PlayerInputActions()
    {
        UnityEngine.Debug.Assert(!m_PlayerCharacterInput.enabled, "This will cause a leak and performance issues, PlayerInputActions.PlayerCharacterInput.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_PlayerAbilityInput.enabled, "This will cause a leak and performance issues, PlayerInputActions.PlayerAbilityInput.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerCharacterInput
    private readonly InputActionMap m_PlayerCharacterInput;
    private List<IPlayerCharacterInputActions> m_PlayerCharacterInputActionsCallbackInterfaces = new List<IPlayerCharacterInputActions>();
    private readonly InputAction m_PlayerCharacterInput_Move;
    public struct PlayerCharacterInputActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerCharacterInputActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PlayerCharacterInput_Move;
        public InputActionMap Get() { return m_Wrapper.m_PlayerCharacterInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerCharacterInputActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerCharacterInputActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerCharacterInputActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerCharacterInputActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IPlayerCharacterInputActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IPlayerCharacterInputActions instance)
        {
            if (m_Wrapper.m_PlayerCharacterInputActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerCharacterInputActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerCharacterInputActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerCharacterInputActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerCharacterInputActions @PlayerCharacterInput => new PlayerCharacterInputActions(this);

    // PlayerAbilityInput
    private readonly InputActionMap m_PlayerAbilityInput;
    private List<IPlayerAbilityInputActions> m_PlayerAbilityInputActionsCallbackInterfaces = new List<IPlayerAbilityInputActions>();
    private readonly InputAction m_PlayerAbilityInput_AbilityTrigger;
    public struct PlayerAbilityInputActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerAbilityInputActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @AbilityTrigger => m_Wrapper.m_PlayerAbilityInput_AbilityTrigger;
        public InputActionMap Get() { return m_Wrapper.m_PlayerAbilityInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerAbilityInputActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerAbilityInputActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerAbilityInputActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerAbilityInputActionsCallbackInterfaces.Add(instance);
            @AbilityTrigger.started += instance.OnAbilityTrigger;
            @AbilityTrigger.performed += instance.OnAbilityTrigger;
            @AbilityTrigger.canceled += instance.OnAbilityTrigger;
        }

        private void UnregisterCallbacks(IPlayerAbilityInputActions instance)
        {
            @AbilityTrigger.started -= instance.OnAbilityTrigger;
            @AbilityTrigger.performed -= instance.OnAbilityTrigger;
            @AbilityTrigger.canceled -= instance.OnAbilityTrigger;
        }

        public void RemoveCallbacks(IPlayerAbilityInputActions instance)
        {
            if (m_Wrapper.m_PlayerAbilityInputActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerAbilityInputActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerAbilityInputActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerAbilityInputActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerAbilityInputActions @PlayerAbilityInput => new PlayerAbilityInputActions(this);
    public interface IPlayerCharacterInputActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
    public interface IPlayerAbilityInputActions
    {
        void OnAbilityTrigger(InputAction.CallbackContext context);
    }
}
